#This file is used to generate a pandas DataFrame out of a .txt file exported from Frantext with cotes and dates. This file contains, for each cote, the corresponding date, the associated decade, and the number of occurrences.
#Created 2015-11-14 by QF
#Modified 2016-03-08 by QF : Added a few comments and a check part at the end. 

import pandas as pd
import numpy as np
import codecs

#The file on which this program operates has to be a .txt file generated by Frantext. Options have to be chosen in the following way:
#par ordre chronologique croissant
#numéroter les résultats
#~(mise en évidence du mot)
#~(respecter la fin de ligne)
#afficher la cote
#afficher la date
#texte en continu
file="/home/quentin/Dropbox/parages.txt"



file_cp = codecs.open(file,encoding='ISO-8859-1')
file_lines = file_cp.readlines()
file_lines_2 = file_lines[1::5] #sélectionne la ligne affichant la cote et la date
data_cot = []
data_dat = []
data_dec = []
for i in range(len(file_lines_2)):
    a = file_lines_2[i]
    a.split('/')
    c = a[:4]
    d = a[5:9]
    if '.' in d:
        d = a[7:11]   
    dec = int(d)
    deca = np.ceil(dec/10)
    data_cot.append(c)
    data_dat.append(d)
    data_dec.append('%i-%i' %((deca-1)*10+1, (deca)*10))
cot_set = list(set(data_cot))
n_occ = []
dat_cot = []
dec_cot = []
for i in range(len(cot_set)):
    n_occ.append(data_cot.count(cot_set[i]))
    dat_cot.append(data_dat[data_cot.index(cot_set[i])])
    dec_cot.append(data_dec[data_cot.index(cot_set[i])])

data_dict = {'cote':cot_set,"date":dat_cot,"decade":dec_cot,"occurrences":n_occ}
data_panda = pd.DataFrame(data_dict)
tot_occ = data_panda['occurrences'].sum()
if tot_occ != len(file_lines_2):
    print('Error: Refinement step: The total number of occurrences does not match Frantext results.')
else:
    print('Refinement step: The total number of occurrences matches Frantext results.')

#Second part - added on 2016-03-08
#In the second part of the program, we build a data frame containing, for each decade, the number of corresponding occurrences.

all_decades = ['%i-%i' %((deca-1)*10+1, (deca)*10) for deca in range(133,203)]

occ_per_decades = [data_panda.loc[data_panda['decade'] ==  all_decades[i], 'occurrences'].sum() for i in range(len(all_decades))]

occ_through_time_dict = {'decade':all_decades, 'occurrences':occ_per_decades}

occ_through_time = pd.DataFrame(occ_through_time_dict)





